config/routes.rb
Rails.application.routes.draw do
  resources :whats_new_items do
    collection do
      post :reorder
    end
  end

end

app/models/whats_new_item.rb
class WhatsNewItem < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/whats_new_items_controller.rb
class WhatsNewItemsController < ApplicationController
  def index
    @whats_new_live = WhatsNewItem.where(release: 'live')
    @whats_new_internal = WhatsNewItem.where(release: 'internal')
    respond_to do |format|
      format.html
      format.json {
        if params[:release] == "internal"
          render :json => @whats_new_internal
       else 
         render :json => @whats_new_live
       end
     }
   end  
  end

  def new
    @item = WhatsNewItem.new
  end

  def create
    @item = WhatsNewItem.new whats_new_item_params
    @item.release = 'internal'
    @item.save
    redirect_to action:  'index'
    flash[:notice] = "#@item.title saved."
  end

  def reorder
    changes = ActiveSupport::JSON.decode(params[:changes])
    console.log(changes)
  end

  def destroy
    @item = WhatsNewItem.find params[:id]
    @item.destroy
  end

  def edit
    @item = WhatsNewItem.find params[:id]
  end

  def update
    @item = WhatsNewItem.find params[:id]

    if @item.update whats_new_item_params
      flash[:notice] = "#{@item.title} saved."
      redirect_to action:  'index'
    else
      render 'edit'
    end
  end

  private
    def whats_new_item_params
      params.require(:whats_new_item).permit(:title, :description, :experiment, :link, :start_date, :end_date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/whats_new_items_helper.rb
module WhatsNewItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/whats_new_items/_form.html.erb
 <%= form_for @item, class: "form-horizontal center" do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title:" %>
        <%= f.text_field :title,  class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Description:" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :experiment, "Experiment:" %>
        <%= f.text_field :experiment, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :link, "Link:" %>
        <%= f.text_field :link, class: "form-control" %>
      </div>
      <div class="col-sm-2 form-group">
	<%= f.label :start_date, "Start Date:" %>
	<%= f.text_field :start_date, class: "form-control datepicker"  %>
      </div>
      <div class="col-sm-2 form-group">
	<%= f.label :end_date, "End Date:" %>
	<%= f.text_field :end_date, class: "form-control datepicker" %>
      </div>
      <div id ="form_buttons" style="float:right; margin-top:10px">
	<%= f.submit "Save", class: "btn btn-default btn-primary", id: "save"%>  
	<%= link_to "Cancel",  whats_new_items_path, class: "btn btn-default btn-danger", id: "cancel"%>
      </div>
 <% end %>




<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  })
</script>

app/views/whats_new_items/destroy.js.erb
$("#<%= @item.id %>").fadeOut();

app/views/whats_new_items/edit.html.erb
<div class="container">
<div class="page-header">
  <h1>Edit Item </h1>
</div>

<%= render 'form' %>
</div>

app/views/whats_new_items/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>What's New Editor</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag "index" %>

  </head>
  

  <body>
<div class="container-fluid">
  <div class="page-header">
    <h1> What's New Editor </h1>
  </div>
    <div class="panel panel-default">
      <div class="panel-heading"><h2> Live Release What's New </h2></div>
      <table class="table connectedSortable" id="live_release">
	<thead>
	  <tr>
            <th class="col-md-2"> Title </th>
            <th class="col-md-4"> Description </th>
            <th class="col-md-1"> Experiment </th>
            <th class="col-md-1"> Link </th>
            <th class="col-md-1"> Start Date </th>
            <th class="col-md-1"> End Date </th>
            <th class="col-md-2"></th>
	  </tr>
	</thead>
	<tbody>
	  <% for item in @whats_new_live do %>
	    <tr class="item" id= <%= item.id %>>
	      <td><%= item.title %></td>
	      <td><%= item.description %></td>
	      <td><%= item.experiment %></td>
	      <td><%= item.link %></td>
	      <td><%= item.start_date %></td>
	      <td><%= item.end_date %></td>
	      <td>
                <%= link_to "Edit", edit_whats_new_item_path(item), class: "btn btn-primary",  role:"button"  %>
		<%= link_to "Delete", whats_new_item_path(item), class: "btn btn-danger",  role:"button", method: :delete, remote: true %>
	      </td>
	    </tr>
	  <% end %>  
	</tbody>
      </table>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading"><h2> Internal Release What's New </h2></div>
      <table class="table connectedSortable" id="internal_release">
	<thead>
          <tr>
            <th class="col-md-2"> Title </th>
            <th class="col-md-4"> Description </th>
            <th class="col-md-1"> Experiment </th>
            <th class="col-md-1"> Link </th>
            <th class="col-md-1"> Start Date </th>
            <th class="col-md-1"> End Date </th>
	    <th class="col-md-2"></th>
	  </tr>
	  </thead>
	<tbody>
          <% for item in @whats_new_internal do %>
            <tr class="item" id= <%= item.id %>>
              <td><%= item.title %></td>
              <td><%= item.description %></td>
              <td><%= item.experiment %></td>
	      <td><%= item.link %></td>
	      <td><%= item.start_date %></td>
	      <td><%= item.end_date %></td>
              <td>
                <%= link_to "Edit", edit_whats_new_item_path(item), class: "btn btn-primary",  role:"button" %>
                <%= link_to "Delete", whats_new_item_path(item), class: "btn btn-danger",  role:"button", method: :delete, remote: true %>
              </td>
            </tr>
          <% end %>
	</tbody>
      </table>
    </div>
    <%= link_to "Add Another Item",  new_whats_new_item_path(@item), class: "btn btn-info", role:"button", id: "add" %>
</div>

    <script>
      var fixHelper = function(e, ui) {
        ui.children().each(function() {
        $(this).width($(this).width());
        });
        return ui;
      };
  
      $(".connectedSortable").sortable({
        items: "tbody > tr",
        helper: "fixHelper",
        axis: "y",
        connectWith: ".connectedSortable",
        dropOnEmpty: true,
        receive: function(e, ui){
          $(this).find("tbody").append(ui.item);   
        },
        stop : function(e, ui){
          newOrder = new Array();
          $('#internal_release tr.item').each(function( index ) {
            id = $(this).attr('id');
            newOrder.push({'id':id, 'release': 'internal', 'position': index});
         }); 
         $('#live_release tr.item').each(function( index ) {
            id = $(this).attr('id');
            newOrder.push({'id':id, 'release': 'live', 'position': index});
          });
       }

      });
      
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  </body>
</html>

app/views/whats_new_items/new.html.erb
<div class="container">
<div class="page-header">
  <h1>New Item </h1>
</div>

<%= render 'form' %>
</div>

app/views/whats_new_items/new.js.erb
$(".modal-body").html(<%= j render 'form' %>)